version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ../db_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=verusen


  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ../code:/home/jovyan/work
    environment:
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
    command: bash -c "pip install -r /home/jovyan/work/requirements.txt && start-notebook.sh"
    depends_on:
      - postgres

  adminer:  
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
