version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "../db_postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo

  pyspark:
    build: .
    volumes:
      - "../code:/opt/spark/work-dir"
    working_dir: /opt/spark/work-dir/
    command: 
      - bash
      - -c
      - |
        spark-submit --jars /opt/spark/work-dir/jdbc/postgresql-42.2.23.jar /opt/spark/work-dir/main.py
    depends_on:
      - postgres
      
  adminer:  
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
